### ISSUE TITLE
[정리] 2022-06-23

### ISSUE THREAD

**Issue by KIJUNG-CHAE** [TypingIsBetterThanLooking/TBTL-Server#3]
**1. 리눅스 커널 소스 파일을 받아서 qemu에 컴파일 시도**
> 커널 소스 파일 다운 -> 커널 소스 make -> 생성된 데비안 파일 적용 -> 재부팅 순으로 컴파일을 시도했다. 데비안 설치 파일 deb파일 생성까지 성공하였으나 dpkg명령어 실행과정에서 문제가 생겼는지 커널 수정이 안됨. make하는 과정에서 문제가 생겼을 것 같다고 생각함!

> 참고한 블로그: https://ndb796.tistory.com/534

**2. 파일을 생성했을 때 커널 내부함수를 통해서 디스크에 할당하는 과정을 추적** #5 
> 컨테이너에서 fio를 이용해서 커널을 추적하려고 했으나 "컨테이너에서 Host OS의 커널을 tracking 할 수 없다. config의 값을 확인해봐라."라는 경고메시지가 나오면서 추적에 실패했다. 이 경고메시지를 해결하기 위해 커널 config파일 수정해봤으나 소용없었다... 그래서 컨테이너에서 생성하든 Host OS에서 생성하든 최종적으로는 Host OS 커널에서 디스크 공간을 맵핑해야 하니 임시방편으로 Host OS에서 함수를 추적해도 된다고 생각했다! Host OS에서 함수를 추적할 때, block을 할당하는 과정뿐만 아니라 메모리, 파일시스템 등 많은 과정이 커널에서 일어난다. I/O요청이 들어왔을 때 어떤 함수가 block과 연관되는 함수인지 찾는 중.

> 너무 감도 못 잡는 상황이라 리눅스 초고수 영인 씨한테 많이 자문해야할 듯.

**3.  컨테이너가 생성되면서 시그룹 서브 디렉토리가 만들어지고 매핑되는 과정을 추적**
> 1, 2번에서 고전 중이라 어느 정도 진전이 있으면 할 예정.

**Comment by silver-whale** [comment]
1번에서 커널 수정이 안 된다는 게 커널 적용이 안 된다는 건진 모르겠지만 아래의 블로그를 참고한 후 나오는 에러 몇 가지를 수정하면 커널 버전이 성공적으로 5.10으로 바뀜.
https://junshim.github.io/linux%20kernel%20study/Linux_Kernel_Compile/

나오는 에러는 약 2~3가지가 있는데, 혹시 몰라 해결책을 첨부함.
http://emal.iptime.org/noriwiki/index.php/Linux_%EB%B9%8C%EB%93%9C
https://stackoverflow.com/questions/61657707/btf-tmp-vmlinux-btf-pahole-pahole-is-not-available

**Comment by Kim0914** [comment]
**1번**

1st) `grep -A100 submenu /boot/grub/grub.cfg | grep menuentry`
명렁어를 입력하면 현재 host OS에 있는 커널 menuentry가 보임.

2nd) Advanced ubuntu용 `$menuentry_id_option` 값을 확인하고,
내가 변경하려는 커널 `$menuentry_id_option` 값을 확인해서
"advanced ubuntu ip option value">"MY_KERNEL_VALU" 문자 만들기

3rd) `vi /etc/default/grub`를 입력하면 grub 설정하는 파일이 열림
GRUB_DEFAULT= 값에 2nd에서 만든 문자 값 넣기
`sudo update-grub`, `sudo reboot` 하고 나면 커스텀 커널로 재부팅 가능 !

-> sudo reboot 명령어 입력 후 반응이 없으면 VNCViewer로 접속하기.

참고: https://blackinkgj.github.io/FedoraKernelInstall/

**Comment by KIJUNG-CHAE** [comment]
커널 변경완료! 재부팅할 때 어느 커널로 부팅할 것인지 지정해줘야 한다.

> -> sudo reboot 명령어 입력 후 반응이 없으면 VNCViewer로 접속하기.

-> 다른 커널로 재부팅하는 과정에서 시간이 소요도기 때문에 ssh connect가 timeout이 나오는 것 같다. 재부팅이 완료될 때까지 기다리면 됨!
